#!/bin/sh

mkdir -p temp
sc source/main.sc temp/main.c

if [ $1 ]
then
  astyle temp/main.c
fi

gcc -Wall -funsigned-char -Werror -Wfatal-errors -o1 -shared -fpic \
$(guile-config compile) $(guile-config link) -lasound -o temp/libguile-sp.so \
temp/main.c -Wl,--version-script=other/export && chmod -R 755 temp
