/* small example that uses the core sound generators via the resonator event.
this example depends on gnuplot to be installed.
see exe/run-example or exe/run-example-sc for how to compile and run with gcc */
#include <sph-sp.h>
#define _sp_rate 48000

/** example demonstrating fundamental event processing with the resonator.
   plots the samples of a low frequency sine wave generated by the resonator */
status_t simple_event_plot() {
  status_declare;
  sp_sample_t* amplitude_modulation;
  sp_time_t duration;
  sp_event_t event;
  sp_resonator_event_config_t* resonator_event_config;
  duration = _sp_rate;
  event = sp_null_event;
  srq((sp_samples_new(duration, (&amplitude_modulation))));
  sp_samples_set(amplitude_modulation, duration, 1);
  srq((sp_event_memory_add((&event), amplitude_modulation)));
  srq((sp_resonator_event_config_new((&resonator_event_config))));
  srq((sp_event_memory_add((&event), resonator_event_config)));
  resonator_event_config->bandwidth_threshold = 50.0;
  (resonator_event_config->channel_config[0]).use = 1;
  (resonator_event_config->channel_config[0]).amod = amplitude_modulation;
  (resonator_event_config->channel_config[0]).amp = 1.0;
  (resonator_event_config->channel_config[0]).frq = 10.0;
  (resonator_event_config->channel_config[0]).bandwidth = 0.0;
  event.start = 0;
  event.end = duration;
  sp_resonator_event((&event), resonator_event_config);
  srq((sp_render_plot(event)));
exit:
  status_return;
}

/* demonstration of the use of event groups, paths, and the resonator as a unified event type */
typedef struct {
  sp_sample_t amp;
} s1_c_t;

status_t s1_prepare(sp_event_t* event) {
  status_declare;
  s1_c_t config_value;
  sp_time_t duration;
  sp_sample_t* amplitude_modulation;
  sp_resonator_event_config_t* resonator_event_config;
  event->prepare = 0;
  duration = (event->end - event->start);
  config_value = *((s1_c_t*)(event->config));
  sp_event_envelope_zero3_srq(event, (&amplitude_modulation), duration, 0.1, (config_value.amp));
  srq((sp_resonator_event_config_new((&resonator_event_config))));
  srq((sp_event_memory_add(event, resonator_event_config)));
  resonator_event_config->bandwidth_threshold = 200.0;
  (resonator_event_config->channel_config[0]).use = 1;
  (resonator_event_config->channel_config[0]).amod = amplitude_modulation;
  (resonator_event_config->channel_config[0]).amp = config_value.amp;
  (resonator_event_config->channel_config[0]).frq = 300.0;
  (resonator_event_config->channel_config[0]).bandwidth = 0.0;
  (resonator_event_config->channel_config[0]).channel = 0;
  (resonator_event_config->channel_config[1]).use = 1;
  (resonator_event_config->channel_config[1]).amod = amplitude_modulation;
  (resonator_event_config->channel_config[1]).amp = (0.5 * config_value.amp);
  (resonator_event_config->channel_config[1]).frq = 3000.0;
  (resonator_event_config->channel_config[1]).bandwidth = 600.0;
  (resonator_event_config->channel_config[1]).channel = 1;
  sp_resonator_event(event, resonator_event_config);
  sp_event_prepare_optional_srq((*event));
exit:
  status_return;
}

sp_define_event(s1_event, s1_prepare, 0);

status_t t1_prepare(sp_event_t* event) {
  status_declare;
  sp_event_t child_event;
  s1_c_t* s1_config;
  sp_time_t tempo;
  sp_time_t times_length;
  sp_time_t times[8];
  sp_size_t index;
  event->prepare = 0;
  times[0] = 0;
  times[1] = 2;
  times[2] = 4;
  times[3] = 6;
  times[4] = 8;
  times[5] = 12;
  times[6] = 14;
  times[7] = 16;
  times_length = 8;
  tempo = (sp_duration(1, 1) / 8);
  sp_event_reset(child_event);
  sp_group_event(event);
  index = 0;
  while (index < times_length) {
    child_event = s1_event;
    sp_event_malloc_type_srq((&child_event), s1_c_t, (&s1_config));
    s1_config->amp = ((index % 2) ? 0.45 : 0.9);
    child_event.config = s1_config;
    child_event.start = (_sp_rate + (tempo * times[index]));
    child_event.end = (child_event.start + sp_duration(1, 6));
    srq((sp_group_add(event, child_event)));
    index += 1;
  }
  sp_event_prepare_optional_srq((*event));
exit:
  status_return;
}

sp_define_event(t1_event, t1_prepare, (sp_duration(3, 1)));

int main() {
  status_declare;
  sp_initialize(1, 2, _sp_rate);
  //srq((simple_event_plot()));
  srq((sp_render_file(t1_event, ("/tmp/sp-example.wav"))));
  //srq((sp_render_plot(t1_event)));
exit:
  sp_deinitialize();
  status_i_return;
}
