typedef uint8_t (*sp_stat_times_f_t)(sp_time_t*, sp_time_t, sp_sample_t*);
typedef uint8_t (*sp_stat_samples_f_t)(sp_sample_t*, sp_time_t, sp_sample_t*);
uint8_t sp_stat_times_range(sp_time_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_times_mean(sp_time_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_times_deviation(sp_time_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_times_median(sp_time_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_times_center(sp_time_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_times_inharmonicity(sp_time_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_times_kurtosis(sp_time_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_times_skewness(sp_time_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_samples_mean(sp_sample_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_samples_deviation(sp_sample_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_samples_inharmonicity(sp_sample_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_samples_median(sp_sample_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_samples_center(sp_sample_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_samples_range(sp_sample_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_samples_kurtosis(sp_sample_t* a, sp_time_t size, sp_sample_t* out);
uint8_t sp_stat_samples_skewness(sp_sample_t* a, sp_time_t size, sp_sample_t* out);
void sp_samples_scale_to_times(sp_sample_t* a, sp_time_t size, sp_time_t max, sp_time_t* out);
sp_time_t sp_stat_unique_max(sp_time_t size, sp_time_t width);
sp_time_t sp_stat_unique_all_max(sp_time_t size);
sp_time_t sp_stat_repetition_all_max(sp_time_t size);
sp_time_t sp_stat_repetition_max(sp_time_t size, sp_time_t width);