#!/bin/sh

optimisation=0
warnings="-Wunused-label -Wunused-value -Wunused-variable"
gcc_options="-Wfatal-errors $warnings -O$optimisation -lasound"
c=source/c-precompiled
dir=temp
file="$dir/libsph-sp.so"
source="$c/main.c"

compile_libsph_sp() {
  f=source/c/foreign
  gcc -Wl,--version-script=other/export -shared -fpic "$source" -o "$file" \
    $gcc_options \
    -Isource/c \
    -Isource/c/foreign/kissfft "$f"/kissfft/kiss_fft.c "$f"/kissfft/tools/kiss_fftr.c
}

compile_test() {
  export LIBRARY_PATH="$PWD/temp"
  gcc "$c/test-main.c" -o temp/test-libsph-sp -lsph-sp -lm $gcc_options
}

mkdir -p "$dir" &&
compile_libsph_sp &&
compile_test
