#!/bin/sh -e

optimisation=3
target_dir=tmp
c=src/c
c_sc=src/c-precompiled
root="$PWD"
compiler=gcc

warnings="-Wall -Wfatal-errors"
gcc_options="-std=c17 -pedantic-errors -D_POSIX_C_SOURCE=200809L -D_FILE_OFFSET_BITS=64 $warnings -fno-common -fno-math-errno -fPIC -O$optimisation -pthread -I$c/foreign -I$c_sc"

compile_sph_sp() {
  src="$c_sc/sph-sp/main.c"
  obj="$target_dir/sph-sp.o"
  lib="$target_dir/libsph-sp.so"
  $compiler $gcc_options -c "$src" -o "$obj"
  $compiler $gcc_options -shared "$obj" -lm -o "$lib"
}

compile_test_sph_sp() {
  $compiler $gcc_options "$c_sc/test/sph-sp.c" -L"$root/$target_dir" -lsph-sp -o "$target_dir/test-libsph-sp"
}

mkdir -p "$target_dir"
compile_sph_sp
compile_test_sph_sp
