#!/bin/sh

# description
# * compiles the sc source code to c
# dependencies
# * sph-sc
# * clang-format

root="$PWD"
sc=source/sc
c="source/c-precompiled"

copy_submodules() {
  # copy code files from submodules.
  # to not have the whole submodule repository in the source directory
  a=submodules/sph-sc-lib/source/sc/main
  b="$sc/foreign/sph"
  mkdir -p "$b" &&
  cp --update --target-directory="$b" \
    "$a/status.sc" "$a/helper.sc" "$a/memreg.sc" "$a/float.sc" \
    "$a/string.sc" "$a/filesystem.sc" "$a/quicksort.sc" "$a/queue.sc" \
    "$a/thread-pool.sc" "$a/futures.sc" "$a/spline-path-h.sc" "$a/spline-path.sc" \
    "$a/types.sc" "$a/random-h.sc" "$a/random.sc" "$a/sph.sc"

}

compile_sc() {
  # create the c source code
  mkdir -p "$c" &&
  cd "$sc" &&
  find -type f -name "*.sc" -exec sc --parents '{}' "$root/$c" \;
  cd "$root" &&
  find "$c" -type f -exec ./exe/format-c -i '{}' \; &&
  mv "$c/main/sph-sp.c" "$c/main/sph-sp.h"
}

copy_submodules &&
compile_sc $@
