#!/bin/sh -e

# description
# * compiles the sc source code to c
# dependencies
# * sph-sc
# * clang-format

root="$PWD"
sc=source/sc
c=source/c-precompiled

compile_sc() {
  # create the c source code
  mkdir -p "$c" &&
  cd "$sc" &&
  find -type f -name "*.sc" -exec sc --parents '{}' "$root/$c" \;
  cd "$root" &&
  find "$c" -type f -exec ./exe/format-c -i '{}' \; &&
  mv "$c/main/sph-sp.c" "$c/main/sph-sp.h"
}

compile_sc
