#!/bin/sh
# list all bindings from sph-sp.sc.
# depends on sc-documentor from sph-sc.

export SC_LOAD_PATH="$PWD/source/sc"
sc-documentor source/sc/sph-sp/*.h.sc --config=other/display-api-config.scm
