#!/bin/sh
# list all bindings from sph-sp.h.
# depends on sc-documentor from sph-sc.

#config="$PWD/other/sc-documentor-config.scm"
export SC_LOAD_PATH="$PWD/source/sc"
#sc-documentor source/sc/main/sph-sp.sc --config="$config" --md-level=2
sc-documentor source/sc/main/sph-sp.sc --md-level=2
