#!/bin/sh -e
# usage: ./exe/install [prefix] [--symlink]

prefix="$1"
mode="$2"

lib_name="libsph-sp.so"
lib_src="$PWD/tmp/$lib_name"
hdr_src="$PWD/src/c-precompiled/sph-sp"
sph_src="$PWD/src/c/foreign/sph-sp/sph"
sc_src="$PWD/src/sc/sph-sp/sc-macros.sc"
lib_root="$prefix/usr/lib"
inc_root="$prefix/usr/include"
sc_root="$prefix/usr/share/sph-sp"

# create dirs with proper permissions
mkdir -p "$lib_root" "$inc_root/sph-sp/sph" "$sc_root"
chmod 755 "$lib_root" "$inc_root" "$inc_root/sph-sp" "$inc_root/sph-sp/sph" "$sc_root"

copy() { install -m "$3" "$1" "$2"; }
link() { ln -sf "$1" "$2"; }

put() {
  src="$1"; dst="$2"; perm="$3"
  if [ "$mode" = "--symlink" ]; then link "$src" "$dst"; else copy "$src" "$dst" "$perm"; fi
}

# library
put "$lib_src" "$lib_root/$lib_name" 755

# headers
put "$hdr_src/sph-sp.h" "$inc_root/sph-sp.h" 644
for h in "$hdr_src"/*.h; do
  [ "$(basename "$h")" = "sph-sp.h" ] && continue
  put "$h" "$inc_root/sph-sp/$(basename "$h")" 644
done
for h in "$sph_src"/*; do
  put "$h" "$inc_root/sph-sp/sph/$(basename "$h")" 644
done

# sc file
put "$sc_src" "$sc_root/sc-macros.sc" 644
