#!/bin/sh

sph_sc_root="$1"
destination="$PWD/source/c/foreign/sph-sc-lib/sph-sp"

mkdir -p "$destination"
cd "$sph_sc_root/source/c-precompiled/sph"
cp -t "$destination" status.h spline-path.h spline-path.c quicksort.c queue.h \
   thread-pool.h thread-pool.c futures.h futures.c float.h float.c array3.c \
   random.h random.c set.c hashtable.c memreg.c helper.h helper.c
