#!/bin/sh

sph_sc_root="$1"
destination="$PWD/src/c/foreign/sph"

if test -d "$destination"
then
  rm "$destination"/*
else
  mkdir -p "$destination"
fi

cd "$sph_sc_root/src/c-precompiled/sph"
cp -t "$destination" status.h spline-path.h spline-path.c quicksort.h queue.h \
   thread-pool.h thread-pool.c futures.h futures.c float.h float.c \
   random.h random.c memreg.h memory.h memory.c array.h
# only for testing
cp -t "$destination" string.h filesystem.h
