#!/bin/sh

# run tests and check for memory leaks with valgrind

options="--leak-check=full --show-leak-kinds=all --track-origins=yes --suppressions=other/valgrind-suppressions"
valgrind --tool=memcheck $options ./exe/test $@
#valgrind --tool=memcheck $options ./tmp/example $@
